### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by rafasancru** [JDipi/Smugmug-Album-Downloader#3]
When I click the download button on the album, nothing happens. The following notice appears in the chrome console attached to the image.
![Captura](https://github.com/JDipi/Smugmug-Album-Downloader/assets/39371499/bcdc263b-adda-41b6-9ef8-552254a9e35d)
The error within the first file cited is this:
![Captura2](https://github.com/JDipi/Smugmug-Album-Downloader/assets/39371499/c1d663cc-677e-4ddb-b027-6152f9b5834c)

**Comment by JDipi** [comment]
I stopped maintaining this project a while back... I don't think it works at all anymore as the Edpuzzle API has likely changed. I may update it in the future. Have you tried using [ading2210's](https://github.com/ading2210/edpuzzle-answers) version?

**Comment by JDipi** [comment]
@rafasancru Hi, if the album you're trying to download is public, could you please send me a link so I can test it out?

P.S. If you saw my last reply in this thread, that was meant for someone else (whoops!)

**Comment by 490398290** [comment]
@JDipi iScript needs to be updated. Download button does nothing atm.

Thanks!

**Comment by JDipi** [comment]
@490398290 Please share the Smugmug album you are trying to download. I just tested the current version of the script and it seems to be working. Also, let me know if you see anything in the console

**Comment by 490398290** [comment]
Fixed

**Comment by JDipi** [comment]
@490398290 Should be fixed, I tested it on the gallery you provided.

**Comment by 490398290** [comment]
Working as expected. Thank you!
